default:
	lessc blk.less blk.css
	lessc index.less index.css
	lessc sign.less sign.css
	lessc proset.less proset.css
	lessc pro.less pro.css
	lessc submit.less submit.css
	lessc manage-pro.less manage-pro.css
